### ISSUE TITLE
Replace pinout PDF, with an image

### ISSUE THREAD

**Issue by jurc192** [Plastic-Scanner/documentation#5]
It's only one page, so an image would make sense (easier usage, faster loading). Preferably in landscape orientation, since that will fit the documentation format nicer

**Comment by Jerzeek** [comment]
I disagree, the PDF is A4 scale so you can print it and have a 1:1 scale of the board with the different pins labeled!

**Comment by jurc192** [comment]
We can still provide downloadable link with PDF for people who want to print it, but I assume most people are just going to scroll through the docs, online - in that case image makes more sense, right?

**Comment by Jerzeek** [comment]
This commit fixes it! c2ee969
